/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gettersSol from "./Getters.sol";
export * as governanceSol from "./Governance.sol";
export * as setupSol from "./Setup.sol";
export * as xBurnMintErc20Sol from "./xBurn&MintERC20.sol";
