/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  XBurnMintERC20Events,
  XBurnMintERC20EventsInterface,
} from "../../../../contracts/ERC20/State.sol/XBurnMintERC20Events";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "fromChain",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "toChain",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "toAddress",
        type: "bytes32",
      },
    ],
    name: "bridgeInEvent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "fromChain",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "toChain",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "fromAddress",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "toAddress",
        type: "bytes32",
      },
    ],
    name: "bridgeOutEvent",
    type: "event",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50601680601d6000396000f3fe6080604052600080fdfea164736f6c634300080a000a";

type XBurnMintERC20EventsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: XBurnMintERC20EventsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class XBurnMintERC20Events__factory extends ContractFactory {
  constructor(...args: XBurnMintERC20EventsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<XBurnMintERC20Events> {
    return super.deploy(overrides || {}) as Promise<XBurnMintERC20Events>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): XBurnMintERC20Events {
    return super.attach(address) as XBurnMintERC20Events;
  }
  override connect(signer: Signer): XBurnMintERC20Events__factory {
    return super.connect(signer) as XBurnMintERC20Events__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): XBurnMintERC20EventsInterface {
    return new utils.Interface(_abi) as XBurnMintERC20EventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): XBurnMintERC20Events {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as XBurnMintERC20Events;
  }
}
