/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as burnMintErc721Sol from "./Burn&MintERC721.sol";
export type { burnMintErc721Sol };
import type * as gettersSol from "./Getters.sol";
export type { gettersSol };
import type * as governanceSol from "./Governance.sol";
export type { governanceSol };
import type * as setupSol from "./Setup.sol";
export type { setupSol };
import type * as stateSol from "./State.sol";
export type { stateSol };
import type * as xBurnMintErc721Sol from "./XBurn&MintERC721.sol";
export type { xBurnMintErc721Sol };
import type * as legacy from "./legacy";
export type { legacy };
