/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC721Extended__factory } from "./IERC721Extended__factory";
export { IWormhole__factory } from "./IWormhole__factory";
