/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface XBurnMintERC20SetupInterface extends utils.Interface {
  functions: {
    "setup(uint16,address,uint8,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "setup"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "setup",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "setup", data: BytesLike): Result;

  events: {};
}

export interface XBurnMintERC20Setup extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: XBurnMintERC20SetupInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    setup(
      chainId: PromiseOrValue<BigNumberish>,
      wormhole: PromiseOrValue<string>,
      finality: PromiseOrValue<BigNumberish>,
      evmChainId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  setup(
    chainId: PromiseOrValue<BigNumberish>,
    wormhole: PromiseOrValue<string>,
    finality: PromiseOrValue<BigNumberish>,
    evmChainId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    setup(
      chainId: PromiseOrValue<BigNumberish>,
      wormhole: PromiseOrValue<string>,
      finality: PromiseOrValue<BigNumberish>,
      evmChainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    setup(
      chainId: PromiseOrValue<BigNumberish>,
      wormhole: PromiseOrValue<string>,
      finality: PromiseOrValue<BigNumberish>,
      evmChainId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    setup(
      chainId: PromiseOrValue<BigNumberish>,
      wormhole: PromiseOrValue<string>,
      finality: PromiseOrValue<BigNumberish>,
      evmChainId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
