/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gettersSol from "./Getters.sol";
export type { gettersSol };
import type * as governanceSol from "./Governance.sol";
export type { governanceSol };
import type * as setupSol from "./Setup.sol";
export type { setupSol };
import type * as xBurnMintErc20Sol from "./xBurn&MintERC20.sol";
export type { xBurnMintErc20Sol };
